module.exports = {
    PASSWORD_NOT_CHANGE:"Password is not change",
    TOKEN_NOT_AVAIL:"Token is not found",
    FAIL_TO_SEND_EMAIL: "Failed to send email",
    LOGIN:"User login successfully",
    USER_REGISTERED: "new user is register",
    EMAIL_ALREADY_EXISTS: "email already register",
    USERID_ALREADY_EXISTS: "userId already register",
    USER_NOT_REGISTERED:"user is not registered",
    NOT_FOUND: "data is not found",
    HELLO: "hello server",
    EMAIL_NOT_REGISTERED: "email is not registered",
    WRONG_PASSWORD: "Wrong password",
    FORBIDDEN: "User is unauthorized",
    CREATED: "task is created",
    UPDATED: "task is updated",
    DELETED: "task is deleted",
    INVALID_OTP: "Invalid otp",
    CHANGE_PASSWORD: "password is change",
    SUCCESS:"Success"
}